const fs = require('fs');
let content = fs.readFileSync('src/components/AuctionPage.tsx', 'utf8');
content = content.replace(/auction\./g, 'auction?.');
content = content.replace(/auction\?\.\?\./g, 'auction?.');
content = content.replace(/normalizeCity\(auction\)/g, 'normalizeCity(auction as any)');
content = content.replace(/normalizeProvince\(auction\?\.province \|\| cityName\)/g, 'normalizeProvince(auction?.province || cityName)');
content = content.replace(/normalizePropertyType\(auction\?\.propertyType\)/g, 'normalizePropertyType(auction?.propertyType as any)');
content = content.replace(/normalizeLocationLabel\(auction\)/g, 'normalizeLocationLabel(auction as any)');
content = content.replace(/getAuctionValuation\(auction\)/g, 'getAuctionValuation(auction as any)');
content = content.replace(/currentAuctionData=\{auction\}/g, 'currentAuctionData={auction as any}');
content = content.replace(/auction=\{auction\}/g, 'auction={auction as any}');
fs.writeFileSync('src/components/AuctionPage.tsx', content);
console.log('Done');
